### PR TITLE
Updated to v0.5.3 with newer conda skeleton

### PR DESCRIPTION
**Pull request by richafrank**
and added Quantopian team as maintainers

---

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by richafrank** [comment]
@conda-forge-admin, please rerender

**Comment by richafrank** [comment]
@alen12345 This ok with you?

**Comment by richafrank** [comment]
@conda-forge/core Could you merge this? Thanks very much.

**Comment by isuruf** [comment]
Can the new maintainers post a comment saying they are fine with being added as maintainers? If so, I'll merge

**Comment by gerrymanoim** [comment]
Yep - All good, thanks!

**Comment by jbredeche** [comment]
I'm good with this, thanks

**Comment by jdricklefs** [comment]
I approve my name being added as a maintainer.

**Comment by fawce** [comment]
yes, thank you!

**Comment by llllllllll** [comment]
I approve my name being added. Thanks.

**Comment by richafrank** [comment]
Thanks @isuruf . I think we have all the approvals now.

**Pull request merged**
